DELIMITER $$
CREATE FUNCTION validarEmail(email VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF 
(email REGEXP '^[a-zA-Z0-9]+@[a-zA-Z]+(\.[a-zA-Z]+)+$',true,false);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION soloLetras(str VARCHAR(100))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (str REGEXP '^[a-zA-Zaáéíóú ]*$',true,false);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION soloNumeros(num BIGINT)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (num REGEXP '^[0-9]*$',true,false);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION validarCiclo(ciclo VARCHAR(2))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF 
(BINARY ciclo = '1S' 
OR BINARY ciclo= '2S' 
OR BINARY ciclo= 'VD' 
OR BINARY ciclo= 'VJ', TRUE, FALSE);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION verificarSeccion(caracter CHAR(1))
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF ( LENGTH(caracter) = 1 AND BINARY caracter = UPPER(caracter), TRUE, FALSE);
END $$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION verificarDiaHorario(num INT)
RETURNS BOOLEAN DETERMINISTIC
BEGIN
RETURN IF (num >= 1 AND num <= 7 , TRUE, FALSE);
END $$
DELIMITER ;
